name: Tests

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/tests.yml"
      - "demo/**/*.typ"
      - "src/**/*.typ"

jobs:
  tests:
    strategy:
      matrix:
        typst-version: ["0.13"]
        include:
          - typst-version: "0.13"
            demo: 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install typst-test from github
        uses: baptiste0928/cargo-install@v3
        with:
          crate: typst-test
          git: https://github.com/tingerrr/typst-test.git
          tag: ci-semi-stable

      - name: Setup typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: ${{ matrix.typst-version }}

      - name: Run test suite
        run: just test

      - name: Build demo
        if: ${{ matrix.demo }}
        run: just demo
